{'Territories':
{'alaska': [67, 54],
'northwest_territory': [145, 52],
'greenland': [352, 28],
'alberta': [114, 93],
'ontario': [186, 91],
'quebec': [250, 92],
'western_united_states': [102, 137],
'eastern_united_states': [171, 148],
'central_america': [114, 202],
'venezuela': [220, 266],
'peru': [230, 349],
'brazil': [278, 330],
'argentina': [240, 410],
'iceland': [415, 56],
'scandinavia': [496, 64],
'ukraine': [558, 91],
'great_britain': [443, 93],
'northern_europe': [495, 102],
'western_europe': [458, 129],
'southern_europe': [520, 129],
'north_africa': [446, 222],
'egypt': [522, 188],
'congo': [522, 291],
'east_africa': [586, 261],
'south_africa': [524, 364],
'madagascar': [609, 363],
'ural': [646, 72],
'siberia': [705, 57],
'yakutsk': [783, 56],
'kamchatka': [873, 58],
'irkutsk': [777, 93],
'afghanistan': [652, 126],
'mongolia': [787, 124],
'china': [776, 168],
'japan': [896, 155],
'middle_east': [590, 166],
'india': [709, 203],
'siam': [796, 230],
'indonesia': [835, 290],
'new_guinea': [932, 311],
'western_australia': [851, 392],
'eastern_australia': [928, 388]},
'Connections':[
['alaska', 'kamchatka'],
['alaska', 'northwest_territory'],
['alaska', 'alberta'],
['northwest_territory', 'greenland'],
['northwest_territory', 'ontario'],
['northwest_territory', 'alberta'],
['greenland', 'iceland'],
['greenland', 'quebec'],
['greenland', 'ontario'],
['greenland', 'northwest_territory'],
['alberta', 'ontario'],
['alberta', 'western_united_states'],
['ontario', 'quebec'],
['ontario', 'eastern_united_states'],
['ontario', 'western_united_states'],
['quebec', 'eastern_united_states'],
['western_united_states', 'eastern_united_states'],
['western_united_states', 'central_america'],
['central_america', 'venezuela'],
['eastern_united_states', 'central_america'],
['venezuela', 'brazil'],
['venezuela', 'peru'],
['peru', 'brazil'],
['peru', 'argentina'],
['brazil', 'north_africa'],
['brazil', 'argentina'],
['iceland', 'scandinavia'],
['iceland', 'great_britain'],
['scandinavia', 'great_britain'],
['scandinavia', 'northern_europe'],
['scandinavia', 'ukraine'],
['great_britain', 'northern_europe'],
['great_britain', 'western_europe'],
['northern_europe', 'ukraine'],
['northern_europe', 'western_europe'],
['northern_europe', 'southern_europe'],
['western_europe', 'southern_europe'],
['western_europe', 'north_africa'],
['southern_europe', 'north_africa'],
['southern_europe', 'egypt'],
['southern_europe', 'middle_east'],
['southern_europe', 'ukraine'],
['ukraine', 'ural'],
['ukraine', 'afghanistan'],
['ukraine', 'middle_east'],
['north_africa', 'egypt'],
['north_africa', 'east_africa'],
['north_africa', 'congo'],
['egypt', 'middle_east'],
['egypt', 'east_africa'],
['congo', 'east_africa'],
['congo', 'south_africa'],
['east_africa', 'middle_east'],
['east_africa', 'madagascar'],
['south_africa', 'madagascar'],
['east_africa', 'south_africa'], 
['ural', 'siberia'],
['ural', 'afghanistan'],
['ural', 'china'],
['siberia', 'yakutsk'],
['siberia', 'irkutsk'],
['siberia', 'mongolia'],
['japan', 'mongolia'],
['japan', 'kamchatka'],
['mongolia', 'china'],
['siberia', 'china'],
['yakutsk', 'irkutsk'],
['yakutsk', 'kamchatka'],
['kamchatka', 'irkutsk'],
['irkutsk', 'mongolia'],
['mongolia', 'kamchatka'],
['afghanistan', 'middle_east'],
['afghanistan', 'india'],
['afghanistan', 'china'],
['china', 'india'],
['china', 'siam'],
['middle_east', 'india'],
['india', 'siam'],
['siam', 'indonesia'],
['indonesia', 'new_guinea'],
['indonesia', 'western_australia'],
['new_guinea', 'western_australia'],
['new_guinea', 'eastern_australia'],
['western_australia', 'eastern_australia']]
}
